baseURL = 'https://ThunderE75.github.io'
languageCode = 'en-us'
title = "Thunder"
siteBanner= 'images/banner.jpg'
theme = 'lightning'
enableEmoji = true

[taxonomies]
  tag = 'tags'
  category = 'categories'

[params.lightning]
  sidePane = true
  countPageItems = 7

[params.lightning.home]
  showBio = false
  showAuthorImg = false
  showHomeBanner = false
  sidePaneTags = true
  showFeatured = true
  showRecent = true
  hideRecentWhenFeatured = true
  countRecent = 5

[params.lightning.side.home]
  sidePaneSticky = false
  taxonomies = ['tags']
  countTaxonomy = 5

[params.lightning.side.single]
  sidePaneSticky = true
  showDetails = true
  showTableOfContents = true
  showAttachments = true
  showRelated = true
  countRelated = 5

[menu]
  [[menu.main]]
      name = "About"
      url = "/about"
      weight = 10

  [[menu.main]]
      name = "Resumé"
      url = "/resume"
      weight = 20

  [[menu.main]]
      name = "Posts"
      url = "/posts"
      weight = 20
  
  [[menu.main]]
    name = "Socials"
    url = "/socials"
    weight = 40


[related]
 includeNewer = true
 [[related.indices]]
  name = 'tags'
  weight = 100

[markup.goldmark.renderer]
unsafe= true